# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 22:17
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name can be located by looking on your credit(EX: YOUR NAME)', max_length=45)),
                ('number', models.CharField(help_text='Your number can be located by looking on your credit(EX: 4242424242424242)', max_length=16, unique=True, validators=[django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(16)])),
                ('exp_month', models.IntegerField(help_text='Format MM (EX: 01, 12)', validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('exp_year', models.IntegerField(help_text='Format YY (EX: 17, 21)')),
                ('due_date', models.IntegerField(help_text='Format DD (EX: 01, 31)', validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)])),
                ('verification_value', models.CharField(help_text='Your CVV number can be located by looking on your credit(EX: 123, 1234)', max_length=4, validators=[django.core.validators.MaxLengthValidator(4), django.core.validators.MinLengthValidator(3)])),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=13)),
                ('invoice', models.DecimalField(decimal_places=2, default=0, help_text='Your invoice total', max_digits=13)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Your balance', max_digits=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit card',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Description of your invoice', max_length=45)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Price', max_digits=13)),
                ('due_date', models.DateField(help_text='Due date')),
                ('pay', models.BooleanField(default=False)),
                ('cards', models.ManyToManyField(blank=True, help_text='Credit cards of wallet', related_name='invoice_credit_card', to='wallet.CreditCard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_limit', models.DecimalField(decimal_places=2, default=0, help_text='Your maximum credit limit', max_digits=13)),
                ('limit', models.DecimalField(decimal_places=2, default=0, help_text='Your credit limit', max_digits=13)),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='your total credit', max_digits=13)),
                ('cards', models.ManyToManyField(help_text='Your credit cards of wallet', to='wallet.CreditCard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
            },
        ),
    ]
